[project]
name = "greenfield-project"
version = "0.1.0"
description = "Greenfield Team Project for AZVIBE"
readme = "README.md"
authors = [
  {name="Michael Sanders", email="mrsande1@asu.edu"},
  {name="Grace Li", email="graceli9095@gmail.com"},
  {name="Jack Markle", email="jack.markle5@gmail.com"},
  {name="Gabriel Scruggs", email="g_works21@hotmail.com"},
  {name="Aahmed Khalil", email=" ahmed.khal718@gmail.com"}
  ]
requires-python = ">=3.12"
dependencies = [
    "annotated-types>=0.7.0",
    "bcrypt==4.1.3",
    "beanie>=2.0.0",
    "email-validator>=2.3.0",
    "fastapi>=0.104.0",
    "gics>=0.2.1",
    "loguru>=0.7.3",
    "motor>=3.7.1",
    "passlib[bcrypt]==1.7.4",
    "phonenumbers>=9.0.18",
    "pydantic>=2.12.4",
    "pydantic-extra-types>=2.10.6",
    "pypdf2>=3.0.1",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.1",
    "python-jose[cryptography]>=3.5.0",
    "requests>=2.32.5",
    "uvicorn[standard]>=0.24.0",
]
